<?php
define(PAGINATE_FRONTEND, 2);
define(PAGINATE_BACKEND, 2);
define(PAGINATE_CATEGORY, 10);
define(NUMBER_PRODUCT_RELATE, 3);
define(IMAGE_STATUS, 1);
define(TYPE_HEADER, 1);
define(TYPE_FOOTER, 2);
define(TYPE_LOGO, 3);